# 应用配置
quarkus.application.name=crm-demo

# H2数据库配置（MySQL模式）
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:crm;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=

# Hibernate配置
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# HTTP配置
quarkus.http.port=8080

# OpenAPI配置
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
